### ISSUE TITLE
Win10 support?

### ISSUE THREAD

**Issue by JHerseth** [acenko/FLACCue#1]
Hey, this looks awesome, but how would I get it running on win10?

**Comment by nick4fake** [comment]
Do you use Plex media server on Win10?
Technically it should be the same as for other OSes.

**Comment by JHerseth** [comment]
@nick4fake yeah, I've yet to build a real mediaserver, so my workstation is also my server at the moment :-/  Guess I'm not really getting how all the stuff ties together.  `FLAC Cue Scanner.py` and `flaccuelib.py` is in `\Plex Media Server\Scanners\Music`, so I figured I should be able to choose this as my musiclibrarys scanner? But I only have _Plex Music_ and _Plex Music Scanner_ there. How does flaccue.py tie into everything?  I guess this needs to run in the background - it takes 2 parameters, a mount point and root. Is root any directory I choose? Is this where I should point plex to find the flacs? Is the root the root directory of my flac/cue  collection?

Thanks :)

**Comment by acenko** [comment]
There is nothing intrinsic to this that should stop it from working in Windows 10, although it may take a little fiddling especially to make FUSE work. The project at https://github.com/billziss-gh/winfsp seems to provide something of a start on this.

In case you haven't seen it, I wrote up a brief description of how everything works, from the perspective of running it on my Synology file server, on the Plex website in this thread:
https://forums.plex.tv/t/flac-cue-sheet-support/292195
You might find some useful information in there.

But in response to the specific questions:
* flaccue.py runs a FUSE file system. This is essentially a software based file system that converts requests for files with a specific filename structure into the specific part of the requested flac file. You'll need to figure out a way for interfacing with this on Windows. In the case of my Synology server, I mount everything in the filesystem ("/") to a flaccue directory ("/flaccue"). This makes my call effectively equivalent to "flaccue.py / /flaccue/" and allows me to easily convert filenames to the FUSE file system by simply prepending "/flaccue" to the full filename, and then modifying the name otherwise to include the time information.
* In flaccuelib.py, I parse .cue files into the appropriate filenames for interfacing with the flaccue.py file system. You'll likely need to change line 125 (parsed_filename = '/flaccue'+full_file) to an appropriate value for whatever you set up for the FUSE filesystem. Basically, your flac and cue files should be in the normal place for Plex and then flaccuelib.py changes the file path Plex sees to include the FUSE file system information. The easiest to implement on Windows may be to give Plex the FUSE file system path and then prepend nothing to the parsed filename--any filename not explicitly labelled for the FUSE filesystem passes through normally. This does require the FUSE filesystem to run for *any* access to your library, though, rather than only when needed.
* After installing flaccuelib.py and FLAC Cue Scanner.py into the Plex directories, you should see a Scanner option near the bottom of the Advanced settings page when you create a new Music library (or edit one). Under that option, I show Plex Music, Plex Music Scanner, flaccuelib, and FLAC Cue Scanner. If you're not seeing the FLAC Cue Scanner option, have you tried rebooting your Plex server? This should be independent of making the FUSE filesystem work.

Hope that helps.

**Comment by JHerseth** [comment]
Thanks for the explanations @acenko - figured out the scanner part. Location of the files should not be in programfiles/plex dir but in %LOCALAPPDATA%. 

I should have enough to get it working I think. Worst case, I'll buy a mATX case and finally build my server :) Thanks for taking the time!

**Comment by aCuria** [comment]
Did it work @JHerseth?

**Comment by JHerseth** [comment]
@aCuria I've switched to linux for my server, so I gave up getting fuse working on WIn10.  Works as it should on nix though :)

**Comment by CarloApri** [comment]
> @aCuria I've switched to linux for my server, so I gave up getting fuse working on WIn10. Works as it should on nix though :)

Could you please help me and explain how to install it on linux? I copied the "Scanners" folder in "Plex Media Server", what else exactly do I need to do?
